services:
  redis:
    image: redis:6-alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
  app:
    build: .
    links:
      - redis
    depends_on:
      - redis