services:
  redis:
    image: redis:6-alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis